version: '3.8'

services:
  # Frontend Angular Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ocr-network
    restart: unless-stopped

  # Backend FastAPI Service (placeholder)
  backend:
    image: python:3.9-slim
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "pip install fastapi uvicorn python-multipart &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - ocr-network
    restart: unless-stopped

networks:
  ocr-network:
    driver: bridge

volumes:
  backend_data:
